import { settlePayment, facilitator } from "thirdweb/x402";
import { createThirdwebClient } from "thirdweb";
import { celo } from "thirdweb/chains";

export const runtime = "edge";

/**
 * Premium AI Market Analysis Endpoint
 * Gated by x402 (Agent Payments Layer)
 * Requires a $0.05 payment in stablecoins on Celo to access.
 */
export async function GET(request: Request) {
  // Validate required environment variables
  const secretKey = process.env.THIRDWEB_SECRET_KEY;
  const feeCollectorAddress = process.env.NEXT_PUBLIC_FEE_COLLECTOR_ADDRESS;

  if (!secretKey) {
    return Response.json(
      { error: "Server configuration error: THIRDWEB_SECRET_KEY not set" },
      { status: 500 }
    );
  }

  if (!feeCollectorAddress) {
    return Response.json(
      { error: "Server configuration error: FEE_COLLECTOR_ADDRESS not set" },
      { status: 500 }
    );
  }

  // Initialize client and facilitator inside the handler
  const client = createThirdwebClient({
    secretKey, // Server-side only
  });

  const thirdwebFacilitator = facilitator({
    client,
    // The address receiving the fee (our platform fee collector)
    serverWalletAddress: feeCollectorAddress,
  });

  // Extract payment signature from headers
  const paymentData = request.headers.get("PAYMENT-SIGNATURE") || request.headers.get("X-PAYMENT");

  // Use settlePayment from thirdweb to verify the x402 payment
  const result = await settlePayment({
    resourceUrl: request.url,
    method: "GET",
    paymentData,
    payTo: feeCollectorAddress,
    network: celo,
    price: "$0.05", // $0.05 USD micro-fee
    facilitator: thirdwebFacilitator,
    routeConfig: {
      description: "Jahpay Premium AI Market Analysis",
      mimeType: "application/json",
    },
  });

  // If payment is settled/verified successfully (status 200)
  if (result.status === 200) {
    const analysis = await generatePremiumAnalysis();
    return Response.json({ data: analysis });
  } else {
    // If no payment or invalid payment, return the 402 Payment Required response generated by thirdweb
    return Response.json(result.responseBody, {
      status: result.status,
      headers: result.responseHeaders,
    });
  }
}

async function generatePremiumAnalysis() {
  const { getMarketSnapshot } = await import('@/lib/agent/agent-intelligence');
  const chainId = parseInt(process.env.NEXT_PUBLIC_CHAIN_ID || '42220', 10);
  const snapshot = await getMarketSnapshot(chainId);

  const usdcUsdt = snapshot.pairs.find((p) => p.from === 'USDC' && p.to === 'USDT');
  const tradable = usdcUsdt?.tradable ?? true;
  const rate = usdcUsdt?.quote.rate ?? 1;
  const deviation = Math.abs(1 - rate);

  return {
    timestamp: snapshot.timestamp,
    overallSentiment: deviation < 0.002 ? 'stable' : deviation < 0.005 ? 'neutral' : 'cautious',
    volatilityIndex: snapshot.volatilityIndex,
    usdcUsdtPoolHealth: {
      liquidityDepth: tradable ? 'optimal' : 'restricted',
      imbalanceWarning: !tradable || deviation > 0.005,
      recommendedAction: tradable
        ? deviation > 0.005
          ? 'Use 0.5–1% slippage for large swaps'
          : 'Execute swaps with minimal slippage (0.1%)'
        : 'Wait — Mento circuit breaker may be active',
      liveRate: rate,
      platformFeePercent: 0.3,
    },
    macroTrends: [
      `Live Mento rate: 1 USDC = ${rate.toFixed(6)} USDT (deviation ${(deviation * 100).toFixed(4)}%).`,
      tradable
        ? 'USDC↔USDT pair is tradable on Mento Protocol.'
        : 'USDC↔USDT pair may be paused — check circuit breaker status.',
      snapshot.celoRate
        ? `CELO/USDC reference: 1 CELO ≈ ${snapshot.celoRate.rate.toFixed(4)} USDC via Mento.`
        : 'CELO swaps: use Ubeswap or Uniswap on Celo for native CELO liquidity.',
    ],
    agentConfidenceScore: tradable && deviation < 0.003 ? 96 : tradable ? 82 : 55,
    disclaimer: 'Analysis uses live Mento oracle data. Not financial advice.',
  };
}
