import { settlePayment, facilitator } from "thirdweb/x402";
import { createThirdwebClient } from "thirdweb";
import { celo } from "thirdweb/chains";

export const runtime = "edge";

/**
 * Premium AI Market Analysis Endpoint
 * Gated by x402 (Agent Payments Layer)
 * Requires a $0.05 payment in stablecoins on Celo to access.
 */
export async function GET(request: Request) {
  // Validate required environment variables
  const secretKey = process.env.THIRDWEB_SECRET_KEY;
  const feeCollectorAddress = process.env.NEXT_PUBLIC_FEE_COLLECTOR_ADDRESS;

  if (!secretKey) {
    return Response.json(
      { error: "Server configuration error: THIRDWEB_SECRET_KEY not set" },
      { status: 500 }
    );
  }

  if (!feeCollectorAddress) {
    return Response.json(
      { error: "Server configuration error: FEE_COLLECTOR_ADDRESS not set" },
      { status: 500 }
    );
  }

  // Initialize client and facilitator inside the handler
  const client = createThirdwebClient({
    secretKey, // Server-side only
  });

  const thirdwebFacilitator = facilitator({
    client,
    // The address receiving the fee (our platform fee collector)
    serverWalletAddress: feeCollectorAddress,
  });

  // Extract payment signature from headers
  const paymentData = request.headers.get("PAYMENT-SIGNATURE") || request.headers.get("X-PAYMENT");

  // Use settlePayment from thirdweb to verify the x402 payment
  const result = await settlePayment({
    resourceUrl: request.url,
    method: "GET",
    paymentData,
    payTo: feeCollectorAddress,
    network: celo,
    price: "$0.05", // $0.05 USD micro-fee
    facilitator: thirdwebFacilitator,
    routeConfig: {
      description: "Jahpay Premium AI Market Analysis",
      mimeType: "application/json",
    },
  });

  // If payment is settled/verified successfully (status 200)
  if (result.status === 200) {
    // Generate the premium market analysis
    const analysis = generatePremiumAnalysis();
    return Response.json({ data: analysis });
  } else {
    // If no payment or invalid payment, return the 402 Payment Required response generated by thirdweb
    return Response.json(result.responseBody, {
      status: result.status,
      headers: result.responseHeaders,
    });
  }
}

// Mock deep market analysis data
function generatePremiumAnalysis() {
  return {
    timestamp: new Date().toISOString(),
    overallSentiment: "bullish",
    volatilityIndex: "low",
    usdcUsdtPoolHealth: {
      liquidityDepth: "optimal",
      imbalanceWarning: false,
      recommendedAction: "Execute large swaps safely",
    },
    macroTrends: [
      "Stablecoin inflows on Celo have increased by 14% over the last 24h.",
      "Mento reserve ratio remains strong, supporting low slippage.",
      "Minimal deviation from the $1 peg expected in the next 7 days."
    ],
    agentConfidenceScore: 98,
    disclaimer: "This analysis is AI-generated and not financial advice."
  };
}
